language: csharp
sudo: required 
mono: none 
dotnet: 6.0
before_install:
 - sudo apt-get update
install:
 - dotnet new tool-manifest --force
 - dotnet tool install Cake.Tool --version 2.2.0
script:
 - dotnet cake build.cake
