name: Push Docker image to GHCR

on: 
  workflow_dispatch:

jobs:
  push-searchfood-forpet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin


    - name: Build the SearchFood-ForPet Docker image
      run: |
        docker build . --tag ghcr.io/ccvaillant1992/SearchFood-ForPet:latest
        docker run ghcr.io/ccvaillant1992/SearchFood-ForPet:latest
        docker push ghcr.io/ccvaillant1992/SearchFood-ForPet:latest
